### ISSUE TITLE
English version

### ISSUE THREAD

**Issue by FloChiff** [FloChiff/DAHNProject#3]
It would be good to enhance the metadata of all the documents with an English version so that there are not only encoded in French.

**Comment by laurentromary** [comment]
Tu penserais à quels types de MD?

**Comment by FloChiff** [comment]
Je souhaitais faire à peu près ce qui avait été fait dans les textes du Berlin intellectuel, pour que les métadonnées soient à la fois en anglais et en français, ce qui sera utile pour les différentes versions du site.
Je ne l'ai pas pas fait dès le début car certaines des balises utilisées dans Lettres et textes (`<seg/>`) ne sont pas considérés comme valides en XML-TEI donc je dois essayer de trouver avant un autre moyen pour ces balises-là.
